# Generated by Django 5.0.6 on 2025-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='votes',
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='option_2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
