# Generated by Django 5.0.6 on 2025-01-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookingamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepayment',
            name='fid',
            field=models.ForeignKey(db_column='fid', default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.flat'),
        ),
    ]
