# Generated by Django 5.0.6 on 2025-01-21 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_maintenancepayment_fid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancepayment',
            name='fid',
            field=models.ForeignKey(db_column='fid', on_delete=django.db.models.deletion.CASCADE, to='myapp.flat'),
        ),
    ]
