# Generated by Django 5.0.6 on 2025-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_maintenancepayment_fid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
