# Generated by Django 5.0.6 on 2025-02-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
