# Generated by Django 5.0.6 on 2025-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
